import 'dart:convert';

import 'package:crypto/crypto.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:ceskina_pro/core/utils/text_normalizer.dart';

/// The audio pack is looked up by hash: the generator names each MP3
/// `{gender}_{sha256}.mp3`, and at runtime CzechTts hashes the text it is about
/// to speak and asks the bucket for that file. If the two sides ever disagree
/// by a single byte, *every* clip silently becomes unreachable and the app
/// falls back to device TTS with no error.
///
/// These expectations are generated by `tool/audio_utterances.py`, which is the
/// single source of truth the generator and coverage tools share. Recompute
/// with:
///   python3 -c "import sys;sys.path.insert(0,'tool');\
///   from audio_utterances import key_for;print(key_for('...'))"
void main() {
  /// Mirrors CzechTts._audioPackKey.
  String audioPackKey(String text) =>
      sha256
          .convert(
            utf8.encode(TextNormalizer.forSpeech(text).trim().toLowerCase()),
          )
          .toString();

  group('audio pack key matches the Python generator', () {
    const expected = <String, String>{
      'Ahoj, jak se máš?':
          'b53fc434ae3f35c21eb5b48b4bc805e9d46c0de967e44f4ce71de7dbc85c127c',
      // Parenthetical hints are stripped before hashing.
      'Dobrý den (formal)':
          '1e9846eea7b1898cd30896699f49c512319ccba03b2279163023f921962de5dc',
      // Fill-in-the-blank markers are stripped ("___" was read as "podtržítko").
      'Mám ___ bratra.':
          '78672c1b123200998c39adb7c32889049d13098ca9c5f0ba62597654b6b1625a',
      // Space before punctuation is closed up.
      'Dám si kávu , prosím !':
          'a4095bc4b6bab6066eaef1e3881a7344b0bba0672ff10bd7749f2fc419b8554b',
      // Case folding must agree on Czech diacritics.
      'ŘEKA':
          '589ae7ada1d41b350a91e6a1decbaca6adef8717494780453e76bb0077fdd9d9',
      // Leading/trailing/repeated whitespace collapses.
      '  Těší   mě  ':
          '2f942df9da2d0782a72f0657aece7cc2aaf6158ebd0bd30626b44608041b7175',
      'Kolik to stojí?':
          '8ac486de2cad848632e78689ebfb8fd066d13be6faad055394c57ca87ee34e25',
    };

    expected.forEach((text, digest) {
      test('"$text"', () => expect(audioPackKey(text), digest));
    });
  });

  test('case-only variants collapse to one clip', () {
    expect(audioPackKey('Kolik to stojí?'), audioPackKey('kolik TO stojí?'));
  });

  test('the generated filename matches the app\'s download pattern', () {
    final name = 'female_${audioPackKey('Ahoj, jak se máš?')}.mp3';
    expect(RegExp(r'^[a-z]+_[0-9a-f]{64}\.mp3$').hasMatch(name), isTrue);
  });
}
